let rawLandUseData = [
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "001",
    Area: "World",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6600,
    Item: "Country area",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 13500322.5135,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "001",
    Area: "World",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6601,
    Item: "Land area",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 13031196.5061,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "001",
    Area: "World",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6602,
    Item: "Agriculture",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 4772427.6272,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "001",
    Area: "World",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6620,
    Item: "Cropland",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 1561667.6816,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "001",
    Area: "World",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6655,
    Item: "Meadows",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 3182766.2667,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "001",
    Area: "World",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6646,
    Item: "Forest land",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 4058930.81,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "001",
    Area: "World",
    "Element Code": 72151,
    Element: "Carbon stock in living biomass",
    "Item Code": 6646,
    Item: "Forest land",
    "Year Code": 2020,
    Year: 2020,
    Unit: "million tonnes",
    Value: 294135.7318,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "001",
    Area: "World",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6717,
    Item: "Naturally regenerating forest",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 3755547.8637,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "001",
    Area: "World",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6716,
    Item: "Planted Forest",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 301451.12,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "001",
    Area: "World",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6670,
    Item: "Other land",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 4199838.0693,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "001",
    Area: "World",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6680,
    Item: "Inland waters",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 427424.2904,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "002",
    Area: "Africa",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6600,
    Item: "Country area",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 3037367.3871,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "002",
    Area: "Africa",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6601,
    Item: "Land area",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 2992174.1094,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "002",
    Area: "Africa",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6602,
    Item: "Agriculture",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 1124047.179,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "002",
    Area: "Africa",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6620,
    Item: "Cropland",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 281861.507,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "002",
    Area: "Africa",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6655,
    Item: "Meadows",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 842097.472,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "002",
    Area: "Africa",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6646,
    Item: "Forest land",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 636638.97,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "002",
    Area: "Africa",
    "Element Code": 72151,
    Element: "Carbon stock in living biomass",
    "Item Code": 6646,
    Item: "Forest land",
    "Year Code": 2020,
    Year: 2020,
    Unit: "million tonnes",
    Value: 50343.8299,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "002",
    Area: "Africa",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6717,
    Item: "Naturally regenerating forest",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 625248.88,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "002",
    Area: "Africa",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6716,
    Item: "Planted Forest",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 11390.11,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "002",
    Area: "Africa",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6670,
    Item: "Other land",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 1231487.9608,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "002",
    Area: "Africa",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6680,
    Item: "Inland waters",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 43896.2777,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "019",
    Area: "Americas",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6600,
    Item: "Country area",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 4065015.005,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "019",
    Area: "Americas",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6601,
    Item: "Land area",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 3866091.6,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "019",
    Area: "Americas",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6602,
    Item: "Agriculture",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 1123522.797,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "019",
    Area: "Americas",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6620,
    Item: "Cropland",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 367297.3042,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "019",
    Area: "Americas",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6655,
    Item: "Meadows",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 754663.4947,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "019",
    Area: "Americas",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6646,
    Item: "Forest land",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 1596895.79,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "019",
    Area: "Americas",
    "Element Code": 72151,
    Element: "Carbon stock in living biomass",
    "Item Code": 6646,
    Item: "Forest land",
    "Year Code": 2020,
    Year: 2020,
    Unit: "million tonnes",
    Value: 137960.8617,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "019",
    Area: "Americas",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6717,
    Item: "Naturally regenerating forest",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 1529595.09,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "019",
    Area: "Americas",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6716,
    Item: "Planted Forest",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 67271.47,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "019",
    Area: "Americas",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6670,
    Item: "Other land",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 1145673.013,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "019",
    Area: "Americas",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6680,
    Item: "Inland waters",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 198553.2507,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 142,
    Area: "Asia",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6600,
    Item: "Country area",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 3199876.5319,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 142,
    Area: "Asia",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6601,
    Item: "Land area",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 3109980.8703,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 142,
    Area: "Asia",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6602,
    Item: "Agriculture",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 1669495.0087,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 142,
    Area: "Asia",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6620,
    Item: "Cropland",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 591266.3055,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 142,
    Area: "Asia",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6655,
    Item: "Meadows",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 1077740.0235,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 142,
    Area: "Asia",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6646,
    Item: "Forest land",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 622686.81,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 142,
    Area: "Asia",
    "Element Code": 72151,
    Element: "Carbon stock in living biomass",
    "Item Code": 6646,
    Item: "Forest land",
    "Year Code": 2020,
    Year: 2020,
    Unit: "million tonnes",
    Value: 37477.0893,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 142,
    Area: "Asia",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6717,
    Item: "Naturally regenerating forest",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 487129.8,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 142,
    Area: "Asia",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6716,
    Item: "Planted Forest",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 135229.57,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 142,
    Area: "Asia",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6670,
    Item: "Other land",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 817799.0516,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 142,
    Area: "Asia",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6680,
    Item: "Inland waters",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 86556.0281,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 150,
    Area: "Europe",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6600,
    Item: "Country area",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 2341972.7895,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 150,
    Area: "Europe",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6601,
    Item: "Land area",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 2213347.1264,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 150,
    Area: "Europe",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6602,
    Item: "Agriculture",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 465979.3525,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 150,
    Area: "Europe",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6620,
    Item: "Cropland",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 288051.5548,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 150,
    Area: "Europe",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6655,
    Item: "Meadows",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 173299.9964,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 150,
    Area: "Europe",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6646,
    Item: "Forest land",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 1017461.22,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 150,
    Area: "Europe",
    "Element Code": 72151,
    Element: "Carbon stock in living biomass",
    "Item Code": 6646,
    Item: "Forest land",
    "Year Code": 2020,
    Year: 2020,
    Unit: "million tonnes",
    Value: 54520.6067,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 150,
    Area: "Europe",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6717,
    Item: "Naturally regenerating forest",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 933626.1637,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 150,
    Area: "Europe",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6716,
    Item: "Planted Forest",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 82748.27,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 150,
    Area: "Europe",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6670,
    Item: "Other land",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 729906.5538,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": 150,
    Area: "Europe",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6680,
    Item: "Inland waters",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 91930.7339,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "009",
    Area: "Oceania",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6600,
    Item: "Country area",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 856090.8,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "009",
    Area: "Oceania",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6601,
    Item: "Land area",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 849602.8,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "009",
    Area: "Oceania",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6602,
    Item: "Agriculture",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 389383.29,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "009",
    Area: "Oceania",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6620,
    Item: "Cropland",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 33191.01,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "009",
    Area: "Oceania",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6655,
    Item: "Meadows",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 334965.28,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "009",
    Area: "Oceania",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6646,
    Item: "Forest land",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 185248.02,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "009",
    Area: "Oceania",
    "Element Code": 72151,
    Element: "Carbon stock in living biomass",
    "Item Code": 6646,
    Item: "Forest land",
    "Year Code": 2020,
    Year: 2020,
    Unit: "million tonnes",
    Value: 13833.344,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "009",
    Area: "Oceania",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6717,
    Item: "Naturally regenerating forest",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 179947.93,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "009",
    Area: "Oceania",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6716,
    Item: "Planted Forest",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 4811.7,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "009",
    Area: "Oceania",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6670,
    Item: "Other land",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 274971.49,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
  {
    "Domain Code": "RL",
    Domain: "Land Use",
    "Area Code (M49)": "009",
    Area: "Oceania",
    "Element Code": 5110,
    Element: "Area",
    "Item Code": 6680,
    Item: "Inland waters",
    "Year Code": 2020,
    Year: 2020,
    Unit: "1000 ha",
    Value: 6488,
    Flag: "E",
    "Flag Description": "Estimated value",
  },
];
// let countryFormat = [
//   {
//     country: "", //row.Area
//     countryArea: "", //row.Item=="Country area"
//     subplots: {
//       landArea: "", //row.Item=="Land area"
//       agriculture: "", //row.Item=="Agriculture"
//       meadows: "", //row.Item=="Meadows"
//       cropland: "", //row.Item=="Cropland"
//       cover: "", //agriculture- (meadows+cropland)
//       forest: "", //row.Item=="Forest land"
//       natural: "", //row.Item=="Naturally regenerating forest" FLOOR
//       planted: "", //row.Item=="Planted Forest" CIEL
//       other: "", //row.Item=="Other land"
//       water: "", //countryArea-landArea
//       inland: "", //row.Item=="Inland waters"
//       coastal: "", //water-inland
//     },
//   },
// ];
export let COLUMN_TOTAL = 160; //x value
export let ROW_TOTAL = 80; //y value
export let countriesSizeArr = [
  //   {
  //     country: "World", //row.Area
  //     countryArea: 0, //row.Item=="Country area"
  //     subplots: {},
  //   },
  {
    country: "Asia", //row.Area
    countryArea: 0, //row.Item=="Country area"
    subplots: {},
  },
  {
    country: "Europe",
    countryArea: 0,
    subplots: {},
  },
  {
    country: "Americas",
    countryArea: 0,
    subplots: {},
  },
  {
    country: "Africa",
    countryArea: 0,
    subplots: {},
  },
  {
    country: "Oceania",
    countryArea: 0,
    subplots: {},
  },
];
let worldArea = 51071659.139;
let map = COLUMN_TOTAL * ROW_TOTAL; //dimensions.ROW_TOTAL * dimensions.COLUMN_TOTAL;

//REFORMATING CURRENT CATEGORIES
rawLandUseData.forEach((row) => {
  if (row.Element == "Area") {
    let countryIndex = countriesSizeArr.map((e) => e.country).indexOf(row.Area);
    // console.log(countryIndex);
    if (countryIndex != -1) {
      if (row.Item == "Country area") {
        countriesSizeArr[countryIndex].countryArea = doMath(row.Value);
      } else if (
        row.Item == "Land area" ||
        row.Item == "Agriculture" ||
        row.Item == "Meadows" ||
        row.Item == "Cropland" ||
        row.Item == "Forest land" ||
        row.Item == "Naturally regenerating forest" ||
        row.Item == "Planted Forest" ||
        row.Item == "Other land"
      ) {
        countriesSizeArr[countryIndex].subplots[row.Item] = doMath(row.Value);
      }
    }
  }
});

//ADDITIONAL BUILT CATEGORIES
// countriesSizeArr.forEach((country) => {
//   let countryIndex = countriesSizeArr
//     .map((e) => e.country)
//     .indexOf(country.country);
//   countriesSizeArr[countryIndex].subplots["Surface"] =
//     countriesSizeArr[countryIndex].subplots["Agriculture"] -
//     (countriesSizeArr[countryIndex].subplots["Meadows"] +
//       countriesSizeArr[countryIndex].subplots["Cropland"]);
//   countriesSizeArr[countryIndex].subplots["Water"] =
//     countriesSizeArr[countryIndex].countryArea -
//     countriesSizeArr[countryIndex].subplots["Land area"];
//   countriesSizeArr[countryIndex].subplots["Coastal waters"] =
//     countriesSizeArr[countryIndex].subplots["Water"] -
//     countriesSizeArr[countryIndex].subplots["Inland waters"];
// });
// console.log(JSON.stringify(countriesSizeArr[0]));
function doMath(val) {
  return Math.ceil((val / worldArea) * map);
}
